# Generated by Django 3.0.6 on 2021-02-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='sunrise', verbose_name='Иконка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunrise.Categories', verbose_name='Категория')),
            ],
        ),
    ]
